extent.reporter.spark.start=true
#folder name& report name
extent.reporter.spark.out=SparkReport/Reports/Spark.html
#foldername
screenshot.dir=./Screenshots/
screenshot.rel.path=../../screenshots/
#customise report folder name by giving base folder & non repeating pattern
basefolder.name=test-output/SparkReport
basefolder.datetimepattern=d-MMM-yy HH-mm-ss
#theme title Encoding give path of extent-config.xml file
extent.reporter.spark.config=src/main/resource/extent-config.xml
systeminfo.user=Pranav Awate
systeminfo.build=0.1
systeminfo.appname=CucumberFramework
